# Generated by Django 4.1.3 on 2022-11-05 23:22

from django.db import migrations, models
import north.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="nculture",
            fields=[
                ("pid", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "pname",
                    models.TextField(
                        default="", max_length=30, verbose_name="PRODUCT NAME"
                    ),
                ),
                ("price", models.IntegerField(default=0)),
                ("desc", models.CharField(max_length=300)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=north.models.path_and_rename
                    ),
                ),
                ("category", models.TextField(max_length=100, verbose_name="category")),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                ("mid", models.IntegerField(primary_key=True, serialize=False)),
                ("pid", models.IntegerField()),
                (
                    "pname",
                    models.TextField(
                        default="", max_length=30, verbose_name="PRODUCT NAME"
                    ),
                ),
                ("price", models.IntegerField(default=0)),
                ("desc", models.CharField(max_length=300)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=north.models.path_and_rename
                    ),
                ),
                ("category", models.TextField(max_length=100, verbose_name="category")),
            ],
        ),
    ]
