# Generated by Django 2.0.8 on 2022-11-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nculture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.TextField(default='', max_length=30, verbose_name='PRODUCT NAME')),
                ('man_date', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='path_and_rename')),
                ('category', models.TextField(default='nullcategory', max_length=100, verbose_name='category')),
            ],
        ),
    ]
