# Generated by Django 2.0.8 on 2022-11-05 19:08

from django.db import migrations, models
import north.models


class Migration(migrations.Migration):

    dependencies = [
        ('north', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nculture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=north.models.path_and_rename),
        ),
    ]
