# Generated by Django 2.0.8 on 2022-11-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('north', '0002_auto_20221106_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nculture',
            name='man_date',
        ),
    ]
