# Generated by Django 4.1.3 on 2022-11-05 20:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("north", "0004_alter_nculture_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="nculture", name="id",),
        migrations.AddField(
            model_name="nculture",
            name="pid",
            field=models.BigAutoField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="nculture",
            name="category",
            field=models.TextField(max_length=100, verbose_name="category"),
        ),
    ]
