# Generated by Django 4.1.3 on 2022-11-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("north", "0005_remove_nculture_id_nculture_pid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nculture",
            name="pid",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
